#!/usr/bin/env ruby
require 'english'
require 'fileutils'
require_relative '../lib/huckleberry'

mode = ARGV[1] ||= "email"
logfile_or_output = ARGV[0]

case logfile_or_output
when nil
  puts Huckleberry::StdoutOutputServer.usage_output
when "keywords"
  puts Huckleberry::StdoutOutputServer.keywords_output
when "email"
  puts Huckleberry::StdoutOutputServer.email_settings_output
when "generate", "g"
  case mode
  when "default"
    FileUtils.mkdir_p 'config/huckleberry'
    FileUtils.cp File.join(Huckleberry.root, "helpers", "default_config_template.yml"), File.join(Dir.pwd, "config", "huckleberry", "huckleberry_config.yml")
  when "blank"
    FileUtils.mkdir_p 'config/huckleberry'
    FileUtils.cp File.join(Huckleberry.root, "helpers", "blank_config_template.yml"), File.join(Dir.pwd, "config", "huckleberry", "huckleberry_config.yml")
  end
else
  Huckleberry::LogSifter.new(logfile: logfile_or_output, mode: mode).carry_log_through_process
end
