#!/usr/bin/env ruby
require 'english'
require_relative '../lib/huckleberry'

mode = ARGV[1] ||= "email"
logfile_or_output = ARGV[0]

case logfile_or_output
when nil
  puts Huckleberry::StdoutOutputServer.usage_output
when "keywords"
  puts Huckleberry::StdoutOutputServer.keywords_output
when "email"
  puts Huckleberry::StdoutOutputServer.email_settings_output
else
  Huckleberry::LogSifter.new(logfile: logfile_or_output, mode: mode).carry_log_through_process
end
